In [1]:
from OpenElectricity_data_manager import OpenElectricityDataManager
import pandas as pd

In [2]:
au = OpenElectricityDataManager(
    network_code='AU',
    start_time='2026-06-20 00:00:00',
    end_time='2026-06-21 00:00:00',
    interval='1h',
    network_2nd_grp='fueltech'
)

[2026-06-26 17:29:41] DEBUG [openelectricity.client.__init__:150] Initialized client with base URL: https://api.openelectricity.org.au/v4/
[2026-06-26 17:29:41] DEBUG [openelectricity.client.__init__:241] Initialized synchronous client

In [3]:
au_market = au.fetch_market_data()

Fetching market data for AU from 2026-06-19 14:00:00 to 2026-06-20 14:00:00
[2026-06-26 17:29:47] DEBUG [openelectricity.client._async_get_market:392] Getting market data for AU (metrics: [<MarketMetric.PRICE: 'price'>, <MarketMetric.DEMAND: 'demand'>, <MarketMetric.DEMAND_GROSS: 'demand_gross'>, <MarketMetric.FLOW_IMPORTS: 'flow_imports'>, <MarketMetric.FLOW_EXPORTS: 'flow_exports'>], interval: 1h, region: None)
[2026-06-26 17:29:47] DEBUG [openelectricity.client._async_get_market:410] Request parameters: {'metrics': ['price', 'demand', 'demand_gross', 'flow_imports', 'flow_exports'], 'interval': '1h', 'date_start': '2026-06-19T14:00:00', 'date_end': '2026-06-20T14:00:00', 'primary_grouping': 'network_region'}
[2026-06-26 17:29:48] DEBUG [openelectricity.client._handle_response:259] Received successful response: 200
finished fetching market data for AU from 2026-06-19 14:00:00 to 2026-06-20 14:00:00

In [4]:
au_market.head()

,interval,price,demand,demand_gross,flow_imports,flow_exports
0,2026-06-20 00:00:00,396.399166,24776.900666,30739.258341,1127.509231,1127.509231
1,2026-06-20 01:00:00,415.410834,26300.924417,29965.591301,902.960076,902.960076
2,2026-06-20 02:00:00,539.083333,28830.720750,30607.800824,758.656354,758.656354
3,2026-06-20 03:00:00,554.638333,31117.442334,31815.857291,868.385662,868.385662
4,2026-06-20 04:00:00,509.415000,31351.493250,31934.694816,813.404576,813.404575

In [12]:
nsw = OpenElectricityDataManager(
    network_code='AU',
    state='TAS1',
    start_time='2026-06-20 00:00:00',
    end_time='2026-06-21 00:00:00',
    interval='1h',
    network_2nd_grp='fueltech'
)

[2026-06-26 17:33:23] DEBUG [openelectricity.client.__init__:150] Initialized client with base URL: https://api.openelectricity.org.au/v4/
[2026-06-26 17:33:23] DEBUG [openelectricity.client.__init__:241] Initialized synchronous client

In [13]:
nsw_market=nsw.fetch_market_data()

Fetching market data for AU from 2026-06-19 14:00:00 to 2026-06-20 14:00:00
[2026-06-26 17:33:25] DEBUG [openelectricity.client._async_get_market:392] Getting market data for AU (metrics: [<MarketMetric.PRICE: 'price'>, <MarketMetric.DEMAND: 'demand'>, <MarketMetric.DEMAND_GROSS: 'demand_gross'>, <MarketMetric.FLOW_IMPORTS: 'flow_imports'>, <MarketMetric.FLOW_EXPORTS: 'flow_exports'>], interval: 1h, region: TAS1)
[2026-06-26 17:33:25] DEBUG [openelectricity.client._async_get_market:410] Request parameters: {'metrics': ['price', 'demand', 'demand_gross', 'flow_imports', 'flow_exports'], 'interval': '1h', 'date_start': '2026-06-19T14:00:00', 'date_end': '2026-06-20T14:00:00', 'primary_grouping': 'network_region', 'network_region': 'TAS1'}
[2026-06-26 17:33:25] DEBUG [openelectricity.client._handle_response:259] Received successful response: 200
finished fetching market data for AU from 2026-06-19 14:00:00 to 2026-06-20 14:00:00

In [14]:
nsw_market.head()

,interval,price,demand,demand_gross,flow_imports,flow_exports
0,2026-06-20 00:00:00,70.303333,1176.135000,1313.841058,0.0,0.000000
1,2026-06-20 01:00:00,68.634167,1158.816667,1277.499892,0.0,0.000000
2,2026-06-20 02:00:00,57.988333,1189.303333,1293.623708,0.0,3.808268
3,2026-06-20 03:00:00,68.646667,1247.737500,1342.883433,0.0,0.000000
4,2026-06-20 04:00:00,54.730833,1248.573333,1331.351983,0.0,0.000000

In [13]:
from openelectricity import OEClient, MarketMetric, DataMetric

In [15]:
help(OEClient.get_market)

Help on function get_market in module openelectricity.client:

get_market(self, network_code: Literal['NEM', 'WEM', 'AU'], metrics: list[openelectricity.types.MarketMetric], interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, primary_grouping: Optional[Literal['network', 'network_region']] = None, network_region: str | None = None) -> openelectricity.models.timeseries.TimeSeriesResponse
    Get market data for specified metrics.

In [33]:
dir(DataMetric)

['EMISSIONS',
 'ENERGY',
 'MARKET_VALUE',
 'POWER',
 'STORAGE_BATTERY',
 '__class__',
 '__doc__',
 '__members__',
 '__module__']

In [29]:
import openelectricity

In [30]:
help(openelectricity)

Help on package openelectricity:

NAME
    openelectricity - OpenElectricity Python SDK

DESCRIPTION
    This package provides a Python client for interacting with the OpenElectricity API.

PACKAGE CONTENTS
    client
    logging
    models (package)
    styles
    types

CLASSES
    openelectricity.client.BaseOEClient(builtins.object)
        openelectricity.client.AsyncOEClient
        openelectricity.client.OEClient
    openelectricity.types.StrEnum(builtins.str, enum.Enum)
        openelectricity.types.DataMetric
        openelectricity.types.FueltechGroupType
        openelectricity.types.MarketMetric
        openelectricity.types.UnitFueltechType
        openelectricity.types.UnitStatusType

    class AsyncOEClient(BaseOEClient)
     |  AsyncOEClient(api_key: str | None = None, base_url: str | None = None, *, proxy: str | None = None, proxy_auth: aiohttp.helpers.BasicAuth | None = None, verify_ssl: bool = True, ssl_context: ssl.SSLContext | None = None, ca_cert: str | os.PathLike[str] | None = None, trust_env: bool = False) -> None
     |
     |  Asynchronous client for the OpenElectricity API.
     |
     |  Method resolution order:
     |      AsyncOEClient
     |      BaseOEClient
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  async __aenter__(self) -> 'AsyncOEClient'
     |
     |  async __aexit__(self, exc_type, exc_val, exc_tb) -> None
     |
     |  __init__(self, api_key: str | None = None, base_url: str | None = None, *, proxy: str | None = None, proxy_auth: aiohttp.helpers.BasicAuth | None = None, verify_ssl: bool = True, ssl_context: ssl.SSLContext | None = None, ca_cert: str | os.PathLike[str] | None = None, trust_env: bool = False) -> None
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  async close(self) -> None
     |      Close the underlying HTTP client.
     |
     |  async get_current_user(self) -> openelectricity.models.user.OpennemUserResponse
     |      Get current user information.
     |
     |  async get_facilities(self, facility_code: list[str] | None = None, status_id: list[openelectricity.types.UnitStatusType | str] | None = None, fueltech_id: list[openelectricity.types.UnitFueltechType | str] | None = None, network_id: list[str] | None = None, network_region: str | None = None) -> openelectricity.models.facilities.FacilityResponse
     |      Get a list of facilities.
     |
     |  async get_facility_data(self, network_code: Literal['NEM', 'WEM', 'AU'], facility_code: str | list[str] | None = None, metrics: list[openelectricity.types.DataMetric] | None = None, interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, unit_code: str | list[str] | None = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get facility data for specified metrics.
     |
     |      Note:
     |          The API accepts at most 30 ``facility_code`` (or ``unit_code``)
     |          items per request. Larger lists raise
     |          :class:`OpenElectricityError` before the request is sent — split
     |          into chunks of 30 or filter further.
     |
     |  async get_market(self, network_code: Literal['NEM', 'WEM', 'AU'], metrics: list[openelectricity.types.MarketMetric], interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, primary_grouping: Optional[Literal['network', 'network_region']] = None, network_region: str | None = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get market data for specified metrics.
     |
     |  async get_network_data(self, network_code: Literal['NEM', 'WEM', 'AU'], metrics: list[openelectricity.types.DataMetric], interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, network_region: str | None = None, fueltech: list[openelectricity.types.UnitFueltechType] | None = None, fueltech_group: list[openelectricity.types.FueltechGroupType] | None = None, primary_grouping: Optional[Literal['network', 'network_region']] = None, secondary_grouping: Optional[Literal['fueltech', 'fueltech_group', 'status', 'renewable']] = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get network data for specified metrics.
     |
     |      Args:
     |          network_code: The network to get data for
     |          metrics: List of metrics to query (e.g. energy, power, price)
     |          interval: The time interval to aggregate by
     |          date_start: Start time for the query
     |          date_end: End time for the query
     |          network_region: Network region to get data for
     |          fueltech: List of individual fuel technologies to filter by (UnitFueltechType enum values)
     |          fueltech_group: List of fuel technology groups to filter by (FueltechGroupType enum values)
     |          primary_grouping: Primary grouping to apply
     |          secondary_grouping: Optional secondary grouping to apply
     |
     |      Returns:
     |          TimeSeriesResponse: Time series data response containing a list of TimeSeries objects
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from BaseOEClient:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

    class DataMetric(StrEnum)
     |  DataMetric(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |
     |  Data metrics available for network and facility data.
     |
     |  Note: ``renewable_proportion`` is a market-level metric and is only
     |  available via :meth:`get_market` with
     |  :attr:`MarketMetric.RENEWABLE_PROPORTION`. It is not exposed on
     |  ``/data/network/`` and so is not listed here.
     |
     |  Method resolution order:
     |      DataMetric
     |      StrEnum
     |      builtins.str
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  EMISSIONS = <DataMetric.EMISSIONS: 'emissions'>
     |
     |  ENERGY = <DataMetric.ENERGY: 'energy'>
     |
     |  MARKET_VALUE = <DataMetric.MARKET_VALUE: 'market_value'>
     |
     |  POWER = <DataMetric.POWER: 'power'>
     |
     |  STORAGE_BATTERY = <DataMetric.STORAGE_BATTERY: 'storage_battery'>
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

    class FueltechGroupType(StrEnum)
     |  FueltechGroupType(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |
     |  Types of fuel technology groups.
     |
     |  Method resolution order:
     |      FueltechGroupType
     |      StrEnum
     |      builtins.str
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  BATTERY = <FueltechGroupType.BATTERY: 'battery'>
     |
     |  COAL = <FueltechGroupType.COAL: 'coal'>
     |
     |  FOSSIL = <FueltechGroupType.FOSSIL: 'fossil'>
     |
     |  GAS = <FueltechGroupType.GAS: 'gas'>
     |
     |  HYDRO = <FueltechGroupType.HYDRO: 'hydro'>
     |
     |  OTHER = <FueltechGroupType.OTHER: 'other'>
     |
     |  RENEWABLE = <FueltechGroupType.RENEWABLE: 'renewable'>
     |
     |  SOLAR = <FueltechGroupType.SOLAR: 'solar'>
     |
     |  WIND = <FueltechGroupType.WIND: 'wind'>
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

    class MarketMetric(StrEnum)
     |  MarketMetric(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |
     |  Market metrics available for market data.
     |
     |  Method resolution order:
     |      MarketMetric
     |      StrEnum
     |      builtins.str
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  CURTAILMENT = <MarketMetric.CURTAILMENT: 'curtailment'>
     |
     |  CURTAILMENT_ENERGY = <MarketMetric.CURTAILMENT_ENERGY: 'curtailment_en...
     |
     |  CURTAILMENT_SOLAR_UTILITY = <MarketMetric.CURTAILMENT_SOLAR_UTILITY: '...
     |
     |  CURTAILMENT_SOLAR_UTILITY_ENERGY = <MarketMetric.CURTAILMENT_SOLAR_UTI...
     |
     |  CURTAILMENT_WIND = <MarketMetric.CURTAILMENT_WIND: 'curtailment_wind'>
     |
     |  CURTAILMENT_WIND_ENERGY = <MarketMetric.CURTAILMENT_WIND_ENERGY: 'curt...
     |
     |  DEMAND = <MarketMetric.DEMAND: 'demand'>
     |
     |  DEMAND_ENERGY = <MarketMetric.DEMAND_ENERGY: 'demand_energy'>
     |
     |  DEMAND_GROSS = <MarketMetric.DEMAND_GROSS: 'demand_gross'>
     |
     |  DEMAND_GROSS_ENERGY = <MarketMetric.DEMAND_GROSS_ENERGY: 'demand_gross...
     |
     |  FLOW_EXPORTS = <MarketMetric.FLOW_EXPORTS: 'flow_exports'>
     |
     |  FLOW_EXPORTS_ENERGY = <MarketMetric.FLOW_EXPORTS_ENERGY: 'flow_exports...
     |
     |  FLOW_IMPORTS = <MarketMetric.FLOW_IMPORTS: 'flow_imports'>
     |
     |  FLOW_IMPORTS_ENERGY = <MarketMetric.FLOW_IMPORTS_ENERGY: 'flow_imports...
     |
     |  GENERATION_RENEWABLE = <MarketMetric.GENERATION_RENEWABLE: 'generation...
     |
     |  GENERATION_RENEWABLE_ENERGY = <MarketMetric.GENERATION_RENEWABLE_ENERG...
     |
     |  GENERATION_RENEWABLE_WITH_STORAGE = <MarketMetric.GENERATION_RENEWABLE...
     |
     |  GENERATION_RENEWABLE_WITH_STORAGE_ENERGY = <MarketMetric.GENERATION_RE...
     |
     |  PRICE = <MarketMetric.PRICE: 'price'>
     |
     |  RENEWABLE_PROPORTION = <MarketMetric.RENEWABLE_PROPORTION: 'renewable_...
     |
     |  RENEWABLE_WITH_STORAGE_PROPORTION = <MarketMetric.RENEWABLE_WITH_STORA...
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

    class OEClient(BaseOEClient)
     |  OEClient(api_key: str | None = None, base_url: str | None = None, *, proxy: str | None = None, proxy_auth: aiohttp.helpers.BasicAuth | None = None, verify_ssl: bool = True, ssl_context: ssl.SSLContext | None = None, ca_cert: str | os.PathLike[str] | None = None, trust_env: bool = False) -> None
     |
     |  Synchronous client for the OpenElectricity API.
     |
     |  It runs aiohttp under the hood and is safe to call from inside an existing
     |  event loop (e.g. a Jupyter/IPython notebook) — when a loop is already
     |  running, requests are dispatched to a worker thread.
     |
     |  Method resolution order:
     |      OEClient
     |      BaseOEClient
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __enter__(self) -> 'OEClient'
     |
     |  __exit__(self, exc_type, exc_val, exc_tb) -> None
     |
     |  __init__(self, api_key: str | None = None, base_url: str | None = None, *, proxy: str | None = None, proxy_auth: aiohttp.helpers.BasicAuth | None = None, verify_ssl: bool = True, ssl_context: ssl.SSLContext | None = None, ca_cert: str | os.PathLike[str] | None = None, trust_env: bool = False) -> None
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  close(self) -> None
     |      Close the underlying HTTP client.
     |
     |  get_current_user(self) -> openelectricity.models.user.OpennemUserResponse
     |      Get current user information.
     |
     |  get_facilities(self, facility_code: list[str] | None = None, status_id: list[openelectricity.types.UnitStatusType | str] | None = None, fueltech_id: list[openelectricity.types.UnitFueltechType | str] | None = None, network_id: list[str] | None = None, network_region: str | None = None) -> openelectricity.models.facilities.FacilityResponse
     |      Get a list of facilities.
     |
     |  get_facility_data(self, network_code: Literal['NEM', 'WEM', 'AU'], facility_code: str | list[str] | None = None, metrics: list[openelectricity.types.DataMetric] | None = None, interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, unit_code: str | list[str] | None = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get facility data for specified metrics.
     |
     |      Note:
     |          The API accepts at most 30 ``facility_code`` (or ``unit_code``)
     |          items per request. Larger lists raise
     |          :class:`OpenElectricityError` before the request is sent — split
     |          into chunks of 30 or filter further.
     |
     |  get_market(self, network_code: Literal['NEM', 'WEM', 'AU'], metrics: list[openelectricity.types.MarketMetric], interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, primary_grouping: Optional[Literal['network', 'network_region']] = None, network_region: str | None = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get market data for specified metrics.
     |
     |  get_network_data(self, network_code: Literal['NEM', 'WEM', 'AU'], metrics: list[openelectricity.types.DataMetric], interval: Optional[Literal['5m', '1h', '1d', '7d', '1M', '3M', 'season', '1y', 'fy']] = None, date_start: datetime.datetime | None = None, date_end: datetime.datetime | None = None, network_region: str | None = None, fueltech: list[openelectricity.types.UnitFueltechType] | None = None, fueltech_group: list[openelectricity.types.FueltechGroupType] | None = None, primary_grouping: Optional[Literal['network', 'network_region']] = None, secondary_grouping: Optional[Literal['fueltech', 'fueltech_group', 'status', 'renewable']] = None) -> openelectricity.models.timeseries.TimeSeriesResponse
     |      Get network data for specified metrics.
     |
     |      Args:
     |          network_code: The network to get data for
     |          metrics: List of metrics to query (e.g. energy, power, price)
     |          interval: The time interval to aggregate by
     |          date_start: Start time for the query
     |          date_end: End time for the query
     |          network_region: Network region to get data for
     |          fueltech: List of individual fuel technologies to filter by (UnitFueltechType enum values)
     |          fueltech_group: List of fuel technology groups to filter by (FueltechGroupType enum values)
     |          primary_grouping: Primary grouping to apply
     |          secondary_grouping: Optional secondary grouping to apply
     |
     |      Returns:
     |          TimeSeriesResponse: Time series data response containing a list of TimeSeries objects
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from BaseOEClient:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

    class UnitFueltechType(StrEnum)
     |  UnitFueltechType(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |
     |  Types of fuel technologies for units.
     |
     |  Method resolution order:
     |      UnitFueltechType
     |      StrEnum
     |      builtins.str
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  AGGREGATOR_DR = <UnitFueltechType.AGGREGATOR_DR: 'aggregator_dr'>
     |
     |  AGGREGATOR_VPP = <UnitFueltechType.AGGREGATOR_VPP: 'aggregator_vpp'>
     |
     |  BATTERY = <UnitFueltechType.BATTERY: 'battery'>
     |
     |  BATTERY_CHARGING = <UnitFueltechType.BATTERY_CHARGING: 'battery_chargi...
     |
     |  BATTERY_DISCHARGING = <UnitFueltechType.BATTERY_DISCHARGING: 'battery_...
     |
     |  BIOENERGY_BIOGAS = <UnitFueltechType.BIOENERGY_BIOGAS: 'bioenergy_biog...
     |
     |  BIOENERGY_BIOMASS = <UnitFueltechType.BIOENERGY_BIOMASS: 'bioenergy_bi...
     |
     |  COAL_BLACK = <UnitFueltechType.COAL_BLACK: 'coal_black'>
     |
     |  COAL_BROWN = <UnitFueltechType.COAL_BROWN: 'coal_brown'>
     |
     |  DISTILLATE = <UnitFueltechType.DISTILLATE: 'distillate'>
     |
     |  EXPORTS = <UnitFueltechType.EXPORTS: 'exports'>
     |
     |  GAS_CCGT = <UnitFueltechType.GAS_CCGT: 'gas_ccgt'>
     |
     |  GAS_OCGT = <UnitFueltechType.GAS_OCGT: 'gas_ocgt'>
     |
     |  GAS_RECIP = <UnitFueltechType.GAS_RECIP: 'gas_recip'>
     |
     |  GAS_STEAM = <UnitFueltechType.GAS_STEAM: 'gas_steam'>
     |
     |  GAS_WCMG = <UnitFueltechType.GAS_WCMG: 'gas_wcmg'>
     |
     |  HYDRO = <UnitFueltechType.HYDRO: 'hydro'>
     |
     |  HYDRO_AND_STORAGE = <UnitFueltechType.HYDRO_AND_STORAGE: 'hydro_and_st...
     |
     |  IMPORTS = <UnitFueltechType.IMPORTS: 'imports'>
     |
     |  INTERCONNECTOR = <UnitFueltechType.INTERCONNECTOR: 'interconnector'>
     |
     |  NUCLEAR = <UnitFueltechType.NUCLEAR: 'nuclear'>
     |
     |  OTHER = <UnitFueltechType.OTHER: 'other'>
     |
     |  PUMPS = <UnitFueltechType.PUMPS: 'pumps'>
     |
     |  SOLAR = <UnitFueltechType.SOLAR: 'solar'>
     |
     |  SOLAR_ROOFTOP = <UnitFueltechType.SOLAR_ROOFTOP: 'solar_rooftop'>
     |
     |  SOLAR_THERMAL = <UnitFueltechType.SOLAR_THERMAL: 'solar_thermal'>
     |
     |  SOLAR_UTILITY = <UnitFueltechType.SOLAR_UTILITY: 'solar_utility'>
     |
     |  WIND = <UnitFueltechType.WIND: 'wind'>
     |
     |  WIND_OFFSHORE = <UnitFueltechType.WIND_OFFSHORE: 'wind_offshore'>
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.


In [34]:
dir(DataMetric)

['EMISSIONS',
 'ENERGY',
 'MARKET_VALUE',
 'POWER',
 'STORAGE_BATTERY',
 '__class__',
 '__doc__',
 '__members__',
 '__module__']

In [35]:
dir(MarketMetric)

['CURTAILMENT',
 'CURTAILMENT_ENERGY',
 'CURTAILMENT_SOLAR_UTILITY',
 'CURTAILMENT_SOLAR_UTILITY_ENERGY',
 'CURTAILMENT_WIND',
 'CURTAILMENT_WIND_ENERGY',
 'DEMAND',
 'DEMAND_ENERGY',
 'DEMAND_GROSS',
 'DEMAND_GROSS_ENERGY',
 'FLOW_EXPORTS',
 'FLOW_EXPORTS_ENERGY',
 'FLOW_IMPORTS',
 'FLOW_IMPORTS_ENERGY',
 'GENERATION_RENEWABLE',
 'GENERATION_RENEWABLE_ENERGY',
 'GENERATION_RENEWABLE_WITH_STORAGE',
 'GENERATION_RENEWABLE_WITH_STORAGE_ENERGY',
 'PRICE',
 'RENEWABLE_PROPORTION',
 'RENEWABLE_WITH_STORAGE_PROPORTION',
 '__class__',
 '__doc__',
 '__members__',
 '__module__']